export const ADD_JWT_WITH_KAKAO = "ADD_JSON_WEB_TOKEN_USING_KAKAO_OAUTH";
export const ADD_JWT_WITH_GOOGLE = "ADD_JSON_WEB_TOKEN_USING_GOOGLE_OAUTH";
export const ADD_UID_OWN = "ADD_UID_OWN_LOGIN";
export const ADD_UID = "ADD_ONLY_UID";
export const ADD_NAME = "ADD_ONLY_NAME";
export const ADD_JWT = "ADD_ONLY_JSON_WEB_TOKEN";
export const LOG_OUT = "LOG_OUT_USER";
