export const ADD_JWT_WITH_KAKAO = "ADD_JSON_WEB_TOKEN_USING_KAKAO_OAUTH";
export const ADD_JWT_WITH_GOOGLE = "ADD_JSON_WEB_TOKEN_USING_GOOGLE_OAUTH";
export const ADD_JWT_OWN = "ADD_JSON_WEB_TOKEN_OWN_LOGIN";
export const LOG_OUT = "LOG_OUT_USER";
